runtime: python39
entrypoint: gunicorn -b :$PORT core.wsgi

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15

env_variables:
  DJANGO_SETTINGS_MODULE: "core.settings"

runtime_config:
  python_version: 3
