# Generated by Django 4.2.7 on 2023-11-13 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_PRODUCTO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=20)),
                ('tipo', models.CharField(db_column='TIPO', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'activo'), ('DESACTIVO', 'desactivo')], db_column='ESTADO', default='activo', max_length=20)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=250)),
            ],
            options={
                'db_table': 'Producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id_valor', models.AutoField(db_column='ID_VALOR', primary_key=True, serialize=False)),
                ('cantidad_de_Personas', models.IntegerField(db_column='CANTIDAD_DE_PERSONAS')),
                ('precio', models.DecimalField(db_column='PRECIO', decimal_places=2, max_digits=9)),
                ('stock', models.IntegerField(db_column='STOCK')),
                ('id_producto', models.ForeignKey(db_column='ID_PRODUCTO', on_delete=django.db.models.deletion.DO_NOTHING, to='interfaceAdmin.producto')),
            ],
            options={
                'db_table': 'Valor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id_presentacion', models.AutoField(db_column='ID_PRESENTACION', primary_key=True, serialize=False)),
                ('imagen', models.ImageField(db_column='IMAGEN', upload_to='img_producto/')),
                ('id_producto', models.ForeignKey(db_column='ID_PRODUCTO', on_delete=django.db.models.deletion.DO_NOTHING, to='interfaceAdmin.producto')),
            ],
            options={
                'db_table': 'PresentacionProducto',
                'managed': True,
            },
        ),
    ]
