# Generated by Django 4.2.7 on 2023-12-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopago',
            name='estado_pago',
            field=models.CharField(choices=[('P', 'Pendiente'), ('S', 'Exitoso'), ('F', 'Fallido')], db_column='ESTADO_PAGO', default='P', max_length=10),
        ),
    ]
