# Generated by Django 4.2.7 on 2023-12-14 22:57

from django.db import migrations, models
import interfaceAdmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceAdmin', '0002_carritocompra_cliente_compra_estadoenvio_estadopago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacionproducto',
            name='imagen',
            field=models.ImageField(db_column='IMAGEN', upload_to='img_producto/', validators=[interfaceAdmin.models.validate_image_file_extension]),
        ),
    ]
