# Generated by Django 4.2.7 on 2023-12-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceAdmin', '0005_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='recibido_por',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='rut',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='seguimiento_numero',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estadoenvio',
            name='nombre',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En camino'), ('R', 'Recibido')], db_column='NOMBRE', max_length=8),
        ),
    ]
