# Generated by Django 4.2.7 on 2023-12-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceAdmin', '0006_envio_recibido_por_envio_rut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='seguimiento_numero',
        ),
    ]
