# Generated by Django 4.2.7 on 2023-12-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceAdmin', '0007_remove_envio_seguimiento_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoenvio',
            name='nombre',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En camino'), ('R', 'Recibido')], db_column='NOMBRE', default='P', max_length=8),
        ),
    ]
