# Generated by Django 4.2.7 on 2023-12-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceAdmin', '0008_alter_estadoenvio_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadopago',
            name='nombre',
        ),
        migrations.AddField(
            model_name='estadopago',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
