# Generated by Django 4.2.7 on 2023-12-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceAdmin', '0009_remove_estadopago_nombre_estadopago_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopago',
            name='detalles_pago',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='estado_pago',
            field=models.CharField(choices=[('P', 'Pendiente'), ('S', 'Exitoso'), ('F', 'Fallido')], db_column='ESTADO_PAGO', default='P', max_length=1),
        ),
    ]
